version: '3'

services:
  NOM_APPLICATION-db:
    container_name: 'NOM_APPLICATION_db'
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'NOM_APPLICATION'
      MYSQL_USER: 'NOM_APPLICATION-user'
      MYSQL_PASSWORD: 'NOM_APPLICATION-pwd'
      MYSQL_ROOT_PASSWORD: 'NOM_APPLICATION-rpwd'
    ports:
      - 3308:3306
    networks:
      - NOM_APPLICATION
  NOM_APPLICATION-ihm:
    container_name: NOM_APPLICATION_ihm
    image: directus/directus:v8-apache
    ports:
      - '8090:80'
    environment:
      DIRECTUS_APP_ENV: 'production'
      DIRECTUS_AUTH_PUBLICKEY: 'NOM_APPLICATION_ihmC69B8E7C437A4E6E16B7A35ACF2C3'
      DIRECTUS_AUTH_SECRETKEY: 'NOM_APPLICATION_ihm'
      DIRECTUS_DATABASE_HOST: 'NOM_APPLICATION_db'
      DIRECTUS_DATABASE_PORT: '3308'
      DIRECTUS_DATABASE_NAME: 'NOM_APPLICATION'
      DIRECTUS_DATABASE_USERNAME: 'NOM_APPLICATION-user'
      DIRECTUS_DATABASE_PASSWORD: 'NOM_APPLICATION-pwd'

      ADMIN_EMAIL: 'kkayefekoua93@gmail.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
    volumes:
      - NOM_APPLICATION-configs:/var/directus/config
      - NOM_APPLICATION-uploads:/var/directus/public/uploads
    networks:
      - NOM_APPLICATION

networks:
  NOM_APPLICATION:
    #name: NOM_APPLICATION
    external: true

volumes:
  NOM_APPLICATION-configs:
  NOM_APPLICATION-uploads:
