name: Directus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-remote-folder:
    name: remote access
    runs-on: ubuntu-latest
    outputs:
      PROJECT_DESCRIPTION: ${{ steps.read-file.outputs.PROJECT_DESCRIPTION }}
    steps:
      - name: 'read file'
        id: read-file
        run: |
          echo 'project<<EOF' >> $GITHUB_OUTPUT
          cat ./project.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: 'File name'
        run: |
          echo '${{ fromJson(env.project).name }}'

      - name: create folder on remote vm
        uses: appleboy/ssh-action@v1.0.0
        env:
          PROJECT_DESCRIPTION: ${{ needs.read-file.outputs.PROJECT_DESCRIPTION }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo mkdir -p /opt/applications/${{ fromJson(env.project).name }}
            sudo chmod ugo+rwx /opt/applications/${{ fromJson(env.project).name }}

  copy-configs-on-remote-vm:
    name: copy-configs-on-remote-vm
    runs-on: ubuntu-latest
    needs: create-remote-folder
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: 'docker-compose.yaml'
          target: /opt/applications/${{ fromJson(env.project).name }}
  run-CMS:
    name: run-CMS
    runs-on: ubuntu-latest
    needs: copy-configs-on-remote-vm
    steps:
      - name: run-CMS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: sudo docker-compose -f /opt/applications/${{ fromJson(env.project).name }}/docker-compose.yaml up -d
