name: Directus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  directus:
    runs-on: ubuntu-latest
    steps:
    - name: copy-docker-compose
      copy: /home/karen/Directus/docker-compose.yaml
      
    - name: build directus
      run: docker compose up